### ISSUE TITLE
Issue in installing SUSHI on Ubuntu

### ISSUE THREAD

**Issue by dktanwar** [uzh/sushi#3]
Hi,

I have successfully carried out all the steps of installation, as explained in [README](https://github.com/uzh/sushi/blob/master/README.rdoc) When I am starting the SUSHI server with `bundle exec rails server -e production` command, I am getting following error:

```
ubuntu@sushi:~/sushi/master$ sudo bundle exec rails server -e production
=> Booting Thin
=> Rails 4.2.10 application starting in production on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
Traceback (most recent call last):
	58: from script/rails:6:in `<main>'
	57: from script/rails:6:in `require'
	56: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	55: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	54: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `server'
	53: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `tap'
	52: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	51: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/server.rb:80:in `start'
	50: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:273:in `start'
	49: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:337:in `wrapped_app'
	48: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/server.rb:61:in `app'
	47: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:209:in `app'
	46: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:300:in `build_app_and_options_from_config'
	45: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:40:in `parse_file'
	44: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:49:in `new_from_string'
	43: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:49:in `eval'
	42: from /home/ubuntu/sushi/master/config.ru:in `<main>'
	41: from /home/ubuntu/sushi/master/config.ru:in `new'
	40: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:55:in `initialize'
	39: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:55:in `instance_eval'
	38: from /home/ubuntu/sushi/master/config.ru:3:in `block in <main>'
	37: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	36: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	35: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	34: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	33: from /home/ubuntu/sushi/master/config/environment.rb:5:in `<top (required)>'
	32: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
	31: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
	30: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
	29: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
	28: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	27: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	26: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	25: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
        53: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `tap'
        52: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        51: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/server.rb:80:in `start'
        50: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:273:in `start'
        49: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:337:in `wrapped_app'
        48: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/server.rb:61:in `app'
        47: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:209:in `app'
        46: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/server.rb:300:in `build_app_and_options_from_config'
        45: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:40:in `parse_file'
        44: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:49:in `new_from_string'
        43: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:49:in `eval'
        42: from /home/ubuntu/sushi/master/config.ru:in `<main>'
        41: from /home/ubuntu/sushi/master/config.ru:in `new'
        40: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:55:in `initialize'
        39: from /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:55:in `instance_eval'
        38: from /home/ubuntu/sushi/master/config.ru:3:in `block in <main>'
        37: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        36: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        35: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        34: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        33: from /home/ubuntu/sushi/master/config/environment.rb:5:in `<top (required)>'
        32: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
        31: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
        30: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
        29: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
        28: from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        27: from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        26: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        25: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
        24: from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
        23: from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        22: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
        21: from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
        20: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
        19: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
        18: from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        17: from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        16: from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        15: from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        14: from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        13: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
        12: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
        11: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
        10: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
         9: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
         8: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
         7: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
         6: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
         5: from /var/lib/gems/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
         4: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
         3: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
         2: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
         1: from /var/lib/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/ubuntu/sushi/master/config/initializers/devise.rb:1:in `<top (required)>': undefined local variable or method `config' for main:Object (NameError)
```

**Comment by masaomi-hatakeyama** [comment]
Thank you for the reporting error.
I guess it is the devise version problem. Let me check it.

**Comment by masaomi-hatakeyama** [comment]
The followings are my command log on Debian (not Ubuntu):
$ uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]

$ git --version
git version 2.1.4

$ bundle --version
Bundler version 1.16.1

$ git clone https://github.com/uzh/sushi.git
$ cd sushi/master/
$ bundle install --path vendor/bundle
$ bundle exec rake secret
xxxx
$ vim config/initializers/devise.rb
(edit)
$ tail -n 2 config/initializers/devise.rb
  config.secret_key = "xxx"
end
$ bundle exec rake db:migrate RAILS_ENV=production

$ mkdir workflow_manager
$ cd workflow_manager/
$ bundle exec workflow_manager -m development
version = 0.4.1
mode = development
DB = PStore
Cluster = LocalComputer
druby://localhost:12345

(back to sushi/ directory in another terminal)
$ bundle exec rails server -e production
=> Booting Thin
=> Rails 4.2.10 application starting in production on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:3000, CTRL+C to stop
------

The 
`
config.secret_key = "xxx" 
`
should be written in config/initilizers/devise.rb between
`
Devise.setup do |config|
  ...
  # here at the end
end
`

**Comment by dktanwar** [comment]
Thank you @masaomi-hatakeyama! I am able to install: `Listening on localhost:3000, CTRL+C to stop`.

Unfortunately, when I open Listening on [localhost:3000](localhost:3000), it says: **We are sorry, page does not exists!**

**Comment by masaomi-hatakeyama** [comment]
Normally, the direct input in the address bar on your browser, http://localhost:3000, returns the top page. Error messages will be usually written in log/production.log. Please check it.

**Comment by dktanwar** [comment]
Here is the error:

```
# Logfile created on 2018-06-08 13:44:37 +0000 by logger.rb/61378
I, [2018-06-16T15:11:02.472797 #14576]  INFO -- : Started GET "/" for 127.0.0.1 at 2018-06-16 15:11:02 +0000
I, [2018-06-16T15:11:02.496338 #14576]  INFO -- : Processing by HomeController#index as HTML
I, [2018-06-16T15:11:02.509298 #14576]  INFO -- : Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.0ms)
F, [2018-06-16T15:11:02.510656 #14576] FATAL -- :
NoMethodError (undefined method `course_users' for #<Rails::Application::Configuration:0x000056429227db40>):
  app/helpers/application_helper.rb:11:in `project_init'
  app/controllers/home_controller.rb:3:in `index'


I, [2018-06-16T15:12:28.551044 #14576]  INFO -- : Started GET "/" for 127.0.0.1 at 2018-06-16 15:12:28 +0000
I, [2018-06-16T15:12:28.557941 #14576]  INFO -- : Processing by HomeController#index as HTML
I, [2018-06-16T15:12:28.562230 #14576]  INFO -- : Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)
F, [2018-06-16T15:12:28.564924 #14576] FATAL -- :
NoMethodError (undefined method `course_users' for #<Rails::Application::Configuration:0x000056429227db40>):
  app/helpers/application_helper.rb:11:in `project_init'
  app/controllers/home_controller.rb:3:in `index'


I, [2018-06-19T10:13:13.173032 #14576]  INFO -- : Started GET "/" for 127.0.0.1 at 2018-06-19 10:13:13 +0000
I, [2018-06-19T10:13:13.177951 #14576]  INFO -- : Processing by HomeController#index as HTML
I, [2018-06-19T10:13:13.185266 #14576]  INFO -- : Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.0ms)
F, [2018-06-19T10:13:13.187250 #14576] FATAL -- :
NoMethodError (undefined method `course_users' for #<Rails::Application::Configuration:0x000056429227db40>):
  app/helpers/application_helper.rb:11:in `project_init'
  app/controllers/home_controller.rb:3:in `index'
```

**Comment by dktanwar** [comment]
Perhaps this is related to the unavailability of the authentication server... if you agree and could just give us a quick pointer as to where this configuration is, we'd try to set up a local ldap and have sushi use it.

**Comment by masaomi-hatakeyama** [comment]
I fixed it. Please git pull and try bundle exec rails server again. I expect then you can run WordCountApp in your environment. You may have another question in SUSHI application configurations. Please do not hesitate to ask me again. I am now making a Docker image.

**Comment by dktanwar** [comment]
Good to know about Docker image. I cannot run `WordCountApp`. It shows error.
![screen shot 2018-06-19 at 14 15 10](https://user-images.githubusercontent.com/8986859/41596646-488ba850-73cb-11e8-8eff-8723980dad0f.png)

**Comment by dktanwar** [comment]
Also, I believe that SUSHI is not yet modified to uptake data from local directory.

**Comment by dktanwar** [comment]
Hi @masaomi-hatakeyama 

Here is the log file:

[production.log](https://github.com/uzh/sushi/files/2122686/production.log)

**Comment by masaomi-hatakeyama** [comment]
You may have missed making database tables

$ bundle exec rake db:migrate RAILS_ENV=production

Can you please try it again? This command does nothing if tables already exist.

**Comment by dktanwar** [comment]
That's true! I missed that. Thank you so much @masaomi-hatakeyama. We are excited to test it now. If we run into any problem, we will let you know.
